# This is a basic workflow to help you get started with Actions

name: Privacera

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v1.1
        with:
          # Azure credentials i.e. output of `az ad sp create-for-rbac --sdk-auth`
          creds: sdf
          # Resource Group Name
          resource-group: sdf
          # AKS Cluster Name
          cluster-name: svs
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Docker Login
        run: docker login --username '${{secrets.DOCKER_LOGIN}}' --password '${{secrets.DOCKER_PASSWORD}}'
      # Runs a set of commands using the runners shell
      - name: PM Update
        run: sh ./public/scripts/test.sh
